---
title: "Resume"
---

###Career Objective
I am graduating in the Spring of 2019 and pursuing an MBA and a part-time job

###Education
-  	Bachelor of Science in Psychology, Human Resource Management Minor
-  	GPA: 3.47, Dean’s List 5 semesters

###Campus Involvement
####Onboarding and Staffing Coordinator 
#####HR Science Research Team
January 2018 - Present

- Trained entire team on new business practices 

- Managed recruiting process for new members 

- Interviewed and selected applicants for admission to research team

- Collaborated with executive leadership team for goal setting 

####Research Associate
#####HR Science Research Team
January 2017 - January 2018

- Completed literature reviews on organizational recruiting and selection, text analytics, and social media

- Interpreted data to identify key attributes in relation to social networks and job performance

- Presented research proposal, [Applicant Reactions to Artificial Intelligence in the Selection Process], at the River Cities I-O Psychology Conference in Chattanooga, TN

###Work Experience
####HR Intern
#####Taft Family Ventures
May 2018 - August 2018

- Created site specific safety manuals for four different construction sites

- Implemented online timeclock software (Pay Clock)

- Attended local SHRM meetings on workplace harassment and workers compensation

- Responsible for daily bank deposits

####Server
#####Hound Ears Country Club
March 2017 - December 2017

- Greeted members in professional and courteous manner

- Discussed description and quality of menu items

- Performed wine and food presentations 

####Houseman
#####Homewood Suites by Hilton
June 2015 - August 2015

- Managed maintenance and cleanliness of entire hotel

-	Supervised organization of room cleaning process through linen inventory management, supervising staff, and troubleshooting to ensure daily deadlines were met

- Opened and Closed kitchen, pool, and lobby areas

###Relevant Coursework

- Negotiation Conflict Resolution

- Strategic Human Resource Management

- Organizational Psychology











